version: '3'

services:
  
  balancer:
    image: nginx
    container_name: balancer
    restart: always
    volumes: 
      - ./docker/nginx/balancer.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    depends_on:
      - php
      - db

  app1:
    image: nginx
    container_name: app1
    restart: always
    volumes: 
      - ./docker/nginx/node.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80
    depends_on:
      - balancer

  app2:
    image: nginx
    container_name: app2
    restart: always
    volumes: 
      - ./docker/nginx/node.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80
    depends_on:
      - balancer

  php:
    build: ./docker/php
    container_name: php
    restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - .:/var/www/html
  
  composer:
    image: composer
    restart: always
    container_name: composer
    volumes:
      - .:/app
    command: install

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
